### ISSUE TITLE
Dúvida teste local

### ISSUE THREAD

**Issue by gartisk** [eletroswing/mercado-pago-split#1]
Olá @eletroswing ,

Primeiramente obrigado pela contribuição.

Tenho uma duvida como testar localmente a aplicação?

Tenho recebido falha 
{"status_code":401,"hint":"unauthorized_error","message":"You dont have the permission to access this route."}

os serviços de MP me parecem estar corretos, os relativos ao Clerk me parecem estar ok também.

E necessário realizar mais alguma outra configuração no serviço?

**Comment by eletroswing** [comment]
Olá @gartisk , obrigado pela interação.
O erro que você está obtendo parte do middleware de autenticação do clerk, presente no arquivo https://github.com/eletroswing/mercado-pago-split/blob/main/middleware/auth.middleware.ts 
Provavelmente ele não está conseguindo validar a mensagem enviada para api. você está enviando o token correto junto de `Bearer`?

Irei investigar o erro mais a fundo, a primeiro momento.

**Comment by gartisk** [comment]
@eletroswing não tenho experiencia no Clerk, mas tentei bypassar essa validação do middleware e tomei um 500 .
{"status_code":500,"hint":"internal_server_error","message":"Something happened on our servers. Please, report this 
issue."}

se quiser podemos conversar no discord brevemente.

**Comment by eletroswing** [comment]
isso acontece por que clerk é fundamental para o sistema, voce pode dar um bypass, nao removelo, trocar o middleware para algo como a seguir deve funcionar: 
```js
import Express from "express";
import { WithAuthProp } from "@clerk/clerk-sdk-node";

import Errors from "./../infra/errors";

export default function authMiddleware(
  request: WithAuthProp<Express.Request>,
  response: Express.Response,
  next: Express.NextFunction
) {
    request.auth.userId = "id-falso";
    return next();
};
 ```

Meu discord é fountaikkj

**Comment by gartisk** [comment]
Funcionou sim!

Te adicionei lá, fica aqui meu contato e agradecimento!
